[package]
name = "nice_level"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
linux-sys = "0.0.0"
nix = { version = "0.27.1", features = ["process"] }
owo-colors = "4.0.0"
